### ISSUE TITLE
Move to MIT license

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence-cube#1]
To follow B3 project recommendations, move from Apache 2.0 to MIT

**Comment by MattBlissett** [comment]
I have added the MIT licence, keeping also the Apache licence.  This might make it a little easier to integrate with existing GBIF code, which is generally Apache licenced.

Inspired by the Rust language doing the same: https://github.com/rust-lang/rust/blob/master/COPYRIGHT
