### ISSUE TITLE
sql downloads - 50km seems to be default gridSize for EEA grids but isn't supported by GBIF_MGRSCode

### ISSUE THREAD

**Issue by jhnwllr** [gbif/occurrence-cube#28]
![image](https://github.com/gbif/occurrence/assets/4245213/aab0d34d-b721-43c3-86e5-e57eb69e20b2)

https://www.eea.europa.eu/en/datahub/datahubitem-view/3c362237-daa4-45e2-8c16-aaadfb1a003b
(download doesn't currently work) 

> gridSize
The grid size in metres of the EEA Reference Grid. Must be 25, 100, 250, 1000, 10000 or 100000.

Other grids are available at other scales, for example here at 10km
https://sdi.eea.europa.eu/data/93315b78-089d-43a5-ac76-b3df627b2e4cf

**Comment by MattBlissett** [comment]
I used 25, 100, 250, 1000, 10000 or 100000 as that's the values given in the [EEA Reference Grid specification](https://sdi.eea.europa.eu/catalogue/srv/api/records/aac8379a-5c4e-445c-b2ef-23a6a2701ef0/attachments/eea_reference_grid_v1.pdf)

I will add 50km.  @peterdesmet, @qgroom, let me know if that's inappropriate.

**Comment by qgroom** [comment]
I can't see any problem with this, though such large grid squares don't seem that useful for analysis of biodiversity data.
