### ISSUE TITLE
LAEA map projection is Europe-specific

### ISSUE THREAD

**Issue by shawndove** [gbif/occurrence-cube#5]
### Description
The currently available occurrence cubes use the LAEA map projection (EPSG: 3035), which is specific to Europe. Given that GBIF data is global, it would probably make sense to either switch to a global projection or allow the user to choose from several options.

### Reasoning
- GBIF data is global in nature and not limited to Europe.
- Using a global map projection would ensure consistency and accuracy when visualizing occurrence data from different regions.
- Allowing users to choose from several projection options would provide flexibility and accommodate specific visualization needs.

**Comment by MattBlissett** [comment]
We now have Extended Quarter Degree Grid Cells (QDGC / EQDGC) and Military Grid Reference System. Both are worldwide.

Thanks,
