### ISSUE TITLE
Setup integration with Zenodo

### ISSUE THREAD

**Issue by peterdesmet** [gbif/occurrence-cube#6]
Setup integration with Zenodo so that GitHub releases of this software are automatically deposited on Zenodo. @MattBlissett will do this under his Zenodo account.

- [x] Setup integration
- [x] Create first release (0.1)
- [x] Test if it was deposited on Zenodo
- [x] Invite @peterdesmet as contributor to the deposit on Zenodo
- [x] Correct/extend metadata on Zenodo
- [x] Link deposit to B-Cubed community on Zenodo
- [x] Later: add `zenodo.json` file to streamline metadata in the future, see #22

**Comment by MattBlissett** [comment]
I can't see a way to invite you as a contributor, but linking to the community says it grants you that permission anyway.

**Comment by peterdesmet** [comment]
Indeed. I was able to edit the deposit and have updated the metadata.
